#!/usr/bin/bash
set -e

# Ensure python3-venv is available for setup-project
apt-get update -q
eatmydata apt-get install python3-venv

# Add the venv (created by setup-project under the persisted tau-data mount)
# to PATH for all login shells
cat <<EOF >/etc/profile.d/tau.sh
export PATH="/home/workshop/.tau/venv/bin:\$PATH"
EOF
