name: Build SDK
permissions: {}

on:
  pull_request:
    branches:
      - latest

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    uses: canonical/sdkcraft-actions/.github/workflows/build.yml@f1471e753bc48c229dc649acbf712ad36fc574ad # main
    with:
      runs-on: '["ubuntu-latest"]'
